--- 
title: "Optimal Regression Design under Second-Order Least Squares Estimator: Theory, Algorithm and Applications"
author: "Chi-Kuang Yeh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is the updated copy of Chi-Kuang Yeh's master thesis."
---

<!-- latex macros -->
\newcommand{\btheta}{\mathbf{\theta}}

# Preface

This thesis is written by Chi-Kuang Yeh, under the guidance of Professor Julie Zhou. I create this bookdown project to fix some typos within it.


## Chi-Kuang Yeh

B.Sc. (Hons.), University of Victoria, 2016

## Supervisory Committee

Supervisor: Dr. [Julie Zhou](https://www.uvic.ca/science/math-statistics/people/home/faculty/zhou_julie.php) (Professor, Department of Mathematics and Statistics)

Departmental Member: Dr. [Xuekui Zhang](https://www.uvic.ca/science/math-statistics/people/home/faculty/zhang_xuekui.php) (Assistant Professor, Department of Mathematics and Statistics)

External Examiner: Dr. [Xiaodai Dong](https://www.uvic.ca/ecs/ece/faculty-and-staff/home/faculty/dongxiaodai.php) (Professor, Department of Electrical and Computer Engineering)

## Abstract

In this thesis, we first review the current development of optimal regression designs under the second-order least squares estimator in the literature. The criteria include A- and D-optimality. We then introduce a new formulation of A-optimality criterion so the result can be extended to c-optimality which has not been studied before. Following Kiefer's equivalence results, we derive the optimality conditions for A-, c- and D-optimal designs under the second-order least squares estimator. In addition, we study the number of support points for various regression models including Peleg models, trigonometric models, regular and fractional polynomial models. A generalized scale invariance property for D-optimal designs is also explored. Furthermore, we discuss one computing algorithm to find optimal designs numerically. Several interesting applications are presented and related MATLAB code are provided in the thesis.

## List of Abbreviations

- **BLUE**:   Best Linear Unbiased Estimator
* **CVX**:     A MATLAB-based modeling system for convex optimization
* **FRM**:    Fractional Polynomial Model
* **GSI**:    Generalized Scale Invariance
* **MATLAB**:   A script language that uses matrix as default format and a computing environment, which is developed by MathWorks
* **OLSE**:   Ordinary Least Squares Estimator
* **SDP**:    Semi-Definite Programming
* **SLSE**:   Second-Order Least Squares Estimator


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
